CREATE TABLE "PdfTemplateSettings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "companyName" TEXT NOT NULL DEFAULT 'Odan Construction',
  "companyAddress" TEXT NOT NULL DEFAULT '19B, Sujatha Avenue, Dehiwala',
  "companyPhone" TEXT NOT NULL DEFAULT '077 811 9382',
  "companyEmail" TEXT NOT NULL DEFAULT 'odanconstruction@gmail.com',
  "logoData" BYTEA,
  "logoMimeType" TEXT,
  "documentTitle" TEXT NOT NULL DEFAULT 'CONSTRUCTION ESTIMATE',
  "footerNote" TEXT NOT NULL DEFAULT 'Note: Amounts shown in LKR. This estimate is based on the quantities and rates listed above and is subject to site conditions and material price variation.',
  "termsConditions" TEXT NOT NULL DEFAULT '',
  "primaryColor" TEXT NOT NULL DEFAULT '#06233F',
  "accentColor" TEXT NOT NULL DEFAULT '#C9A44C',
  "fontFamily" TEXT NOT NULL DEFAULT 'Helvetica',
  "headerLayout" TEXT NOT NULL DEFAULT 'LEFT',
  "watermarkEnabled" BOOLEAN NOT NULL DEFAULT true,
  "watermarkOpacity" DOUBLE PRECISION NOT NULL DEFAULT 0.045,
  "watermarkSize" TEXT NOT NULL DEFAULT 'MEDIUM',
  "tableStyle" TEXT NOT NULL DEFAULT 'NAVY',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PdfTemplateSettings_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "PdfTemplateSettings_singleton" CHECK ("id" = 1)
);
